"""create tables

Revision ID: 384040bdb4dc
Revises: 
Create Date: 2024-08-06 01:45:08.426515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384040bdb4dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boundary_point',
    sa.Column('winner_boundary_points', sa.Float(), nullable=False),
    sa.Column('pre_winner_boundary_points', sa.Float(), nullable=False),
    sa.Column('years', sa.Integer(), nullable=False),
    sa.Column('title', sa.Enum('vseros', 'region', 'vp', 'mosh', 'finashka', 'sibiriada', 'kondrat', name='olymptitle'), nullable=False),
    sa.Column('user_class', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('olymp_point',
    sa.Column('title', sa.Enum('vseros', 'region', 'vp', 'mosh', 'finashka', 'sibiriada', 'kondrat', name='olymptitle'), nullable=False),
    sa.Column('grade', sa.Enum('winner', 'pre_winner', 'loser', name='grades'), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('user_class', sa.SmallInteger(), nullable=True),
    sa.Column('names', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('school', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passing_point',
    sa.Column('passing_points', sa.Float(), nullable=False),
    sa.Column('years', sa.Integer(), nullable=False),
    sa.Column('title', sa.Enum('vseros', 'region', 'vp', 'mosh', 'finashka', 'sibiriada', 'kondrat', name='olymptitle'), nullable=False),
    sa.Column('user_class', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passing_point')
    op.drop_table('olymp_point')
    op.drop_table('boundary_point')
    # ### end Alembic commands ###
